name: Build and Deploy Machine_Learning-Based_Assessment_of_NLFSR_Strength PDF

on:
  push:
    branches:
      - master
    paths:
      - 'docs/Machine_Learning-Based_Assessment_of_NLFSR_Strength.tex'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile PDF using LaTeX Action
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Machine_Learning-Based_Assessment_of_NLFSR_Strength.tex
          working_directory: docs
          latexmk_use_lualatex: false  # set true if needed
          continue_on_error: false

      - name: Switch to deploy branch and update PDF
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin deploy:deploy || git checkout --orphan deploy
          git checkout deploy

          git add docs/Machine_Learning-Based_Assessment_of_NLFSR_Strength.pdf
          git commit -m "Update PDF from master" || echo "No changes to commit"
          git push origin deploy
