name: Build Proposal and Deploy PDF

on:
    push:
        paths:
            - 'docs/proposal.tex'

jobs:
    build-proposal:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
            uses: actions/checkout@v3

        - name: Install texlive-full
            run: |
                sudo apt-get update
                sudo apt-get install -y texlive-full

        - name: Build proposal.tex
            run: |
                latexmk -pdf -interaction=nonstopmode -output-directory=output docs/proposal.tex

        - name: Upload PDF to deploy branch
            if: success()
            run: |
                git config user.name "GitHub Actions"
                git config user.email "actions@github.com"
                git checkout -b deploy || git checkout deploy
                mv output/proposal.pdf proposal.pdf
                git add proposal.pdf
                git commit -m "Update proposal.pdf"
                git push origin deploy