name: Build Proposal and Deploy PDF

on:
  push:
    paths:
      - 'docs/proposal.tex'

jobs:
  build-proposal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to push later

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: docs/proposal.tex
          working_directory: .
          output_directory: output

      - name: Move and commit generated PDF
        run: |
          mv output/proposal.pdf proposal.pdf
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout deploy || git checkout -b deploy
          git add proposal.pdf
          git commit -m "Update proposal.pdf" || echo "No changes to commit"
          git push origin deploy
