name: Build LaTeX Docs

on:
  push:
    branches:
      - deploy
    paths:
      - 'docs/**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TeX Live (full)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX files
        run: |
          mkdir -p build
          for file in docs/*.tex; do
            pdflatex -output-directory=build "$file"
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdfs
          path: build/*.pdf
